# Generated by Django 2.2.6 on 2019-10-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Direction', '0002_direction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Direction.Direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['position'],
            },
        ),
    ]
