# Generated by Django 2.2.6 on 2019-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0002_auto_20191029_1921'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(related_name='courses', to='Lesson.Lesson', verbose_name='Уроки'),
        ),
    ]
