# Generated by Django 2.2.6 on 2019-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Lesson.Lesson', verbose_name='Уроки'),
        ),
    ]
