# Generated by Django 2.2.6 on 2019-10-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('material1', models.CharField(max_length=255, verbose_name='Материал 1')),
                ('material2', models.TextField(verbose_name='Материал 2')),
                ('material3', models.ImageField(upload_to='lesson_materials/%Y/%m/%d/', verbose_name='Материал 3')),
                ('material4', models.FileField(upload_to='lesson_materials/%Y/%m/%d/', verbose_name='Материал 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('anons', models.TextField(verbose_name='Анонс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_to_video', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('link_to_file', models.CharField(max_length=255, verbose_name='Ссылка на файл')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('courses', models.ManyToManyField(related_name='lessons', to='Course.Course', verbose_name='Курсы')),
                ('materials', models.ManyToManyField(related_name='lessons', to='Lesson.LessonMaterial', verbose_name='Материалы к уроку')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
