# Generated by Django 2.2.6 on 2019-10-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'verbose_name': 'Материал к уроку', 'verbose_name_plural': 'Материалы к уроку'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='courses',
        ),
    ]
