# Generated by Django 2.2.6 on 2019-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0002_auto_20191029_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='Lesson.LessonMaterial', verbose_name='Материалы к уроку'),
        ),
    ]
