# Generated by Django 2.2.6 on 2019-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0003_auto_20191029_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='anons',
            field=models.TextField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_to_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_to_video',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Материал 1'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material2',
            field=models.TextField(blank=True, verbose_name='Материал 2'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material3',
            field=models.ImageField(blank=True, upload_to='lesson_materials/%Y/%m/%d/', verbose_name='Материал 3'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material4',
            field=models.FileField(blank=True, upload_to='lesson_materials/%Y/%m/%d/', verbose_name='Материал 4'),
        ),
    ]
